Repository chaosblade-io/chaosblade-exec-jvm, pull requests merged in 2020-11, with the labels that each got.

#147 feature: add mongodb plugin.
  chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/pom.xml
  chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBCollectionMatcherSpec.java
  chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBConstant.java
  chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBDatabaseMatcherSpec.java
  chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBEnhancer.java
  chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBModelSpec.java
  chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBPlugin.java
  chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBPointCut.java
  chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBSqlTypeMatcherSpec.java
  chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin
  chaosblade-exec-plugin/pom.xml
Labels: kind/feature

#159 support redisson
  chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/pom.xml
  chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/src/main/java/com/alibaba/chaosblade/exec/plugin/redisson/RedissonCmdTypeMatcherSpec.java
  chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/src/main/java/com/alibaba/chaosblade/exec/plugin/redisson/RedissonConstant.java
  chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/src/main/java/com/alibaba/chaosblade/exec/plugin/redisson/RedissonEnhancer.java
  chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/src/main/java/com/alibaba/chaosblade/exec/plugin/redisson/RedissonKeyMatcherSpec.java
  chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/src/main/java/com/alibaba/chaosblade/exec/plugin/redisson/RedissonModelSpec.java
  chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/src/main/java/com/alibaba/chaosblade/exec/plugin/redisson/RedissonPlugin.java
  chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/src/main/java/com/alibaba/chaosblade/exec/plugin/redisson/RedissonPointCut.java
  chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin
  chaosblade-exec-plugin/pom.xml
Labels: enhancement

#157 fix:修复编译java代码会导致内存泄露问题
  chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/script/java/JavaCodeScriptEngine.java
Labels: bug
